export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  PROFIL: '/profil',
  MEMBRES: '/membres',
  MEMBRE_DETAIL: '/membres/:id',
  MEMBRE_CREATION: '/membres/nouveau',
  PAIEMENTS: '/paiements',
  PAIEMENT_CREATION: '/paiements/nouveau',
  PAIEMENT_WAVE: '/paiements/wave',
  DEPENSES: '/depenses',
  DEPENSE_CREATION: '/depenses/nouvelle',
  PARAMETRES: '/parametres',
  LOGS: '/logs',
  RAPPORTS: '/rapports',
  RAPPORT_DETAIL: '/rapports/:id',
  ARRIERES: '/arrieres',
  NOT_FOUND: '*',
} as const;
